Fix the example code so that it works
Without this fix, the example code produces this error message:

Traceback (most recent call last):
  File "example_rise_set.py", line 85, in <module>
    (deneb_transit, deneb_rise, deneb_set) =
rise_set_of_deneb_from_maui()
  File "example_rise_set.py", line 50, in rise_set_of_deneb_from_maui
    (transit, rise, setting) = calc_rise_set(deneb, maui, date)
  File
".../site-packages/rise_set/astrometry.py",
line 599, in calc_rise_set
    date = date.replace(hour=0, minute=0, second=0, microsecond=0)
TypeError: replace() takes at most 3 arguments (4 given)